# fewer restrictions in test code
allow-expect-in-tests = true # expect_used
allow-unwrap-in-tests = true # unwrap_used
allow-panic-in-tests = true # panic
allow-indexing-slicing-in-tests = true # indexing_slicing

# const slices ok
suppress-restriction-lint-in-const = true # indexing_slicing: suppress in const contexts where .get() is unavailable.
allow-expect-in-consts = true # expect_used
allow-unwrap-in-consts = true # unwrap_used

# other lints
allow-exact-repetitions = true # module_name_repetitions
allow-comparison-to-zero = true # modulo_arithmetic: allow comparing modulo operation to zero