//! In-crate tests: independent Python-reference fixtures, permutation
//! sanity, and constant hygiene.
//!
//! Fixture provenance: every fixture below was generated by the independent
//! Python reference implementation (stdlib only), never by this crate.
//! Regeneration recipe (`ks` is the cyclic key schedule; `len(ks) = 1` is
//! the single-key cipher):
//!
//! ```text
//! import hashlib
//! p = 0x40000000000000000000000000000000224698fc094cf91b992d30ed00000001
//! PERSON = b"Tachyon-MiMCx5v1"
//! def consts(r):
//!     out = [0]
//!     for i in range(1, r):
//!         h = hashlib.blake2b(i.to_bytes(8, "little"), digest_size=64,
//!                             person=PERSON).digest()
//!         out.append(int.from_bytes(h, "little") % p)
//!     return out
//! def mimc(ks, x, cs):
//!     r = len(cs)
//!     for i, c in enumerate(cs):
//!         x = pow((x + ks[i % len(ks)] + c) % p, 5, p)
//!     return (x + ks[r % len(ks)]) % p
//! ```
//!
//! All limbs are little-endian `u64`s as consumed by `Fp::from_raw`.

mod pp;

use alloc::vec::Vec;

use blake2b_simd::Params;
use ff::{Field as _, FromUniformBytes as _, PrimeField as _};
use pasta_curves::Fp;

/// The indexed Blake2b round-constant chain, mirrored from the Python
/// reference: `c_0 = 0`, `c_i = from_uniform(Blake2b-512(i LE, person))`.
/// Pinned [`crate::Spec::CONSTANTS`] tables are cross-checked against it.
fn derive_chain(personalization: &[u8; 16], rounds: usize) -> Vec<Fp> {
    (0u64..)
        .take(rounds)
        .map(|index| {
            if index == 0 {
                Fp::ZERO
            } else {
                let digest = Params::new()
                    .hash_length(64)
                    .personal(personalization)
                    .to_state()
                    .update(&index.to_le_bytes())
                    .finalize();
                Fp::from_uniform_bytes(digest.as_array())
            }
        })
        .collect()
}

/// Number of random samples per randomized test.
const SAMPLES: usize = 8;

/// Blake2b personalization of the [`crate::tachyon::TachyonP5R64`]
/// round-constant chain.
const PERSONALIZATION: &[u8; 16] = b"Tachyon-MiMCx5v1";

/// `sbox_pow^{-1} mod (p - 1)` as little-endian limbs for [`ff::Field::pow`],
/// derived from the field itself rather than pinned.
///
/// The canonical bytes of `-1` are `p - 1`; because
/// `gcd(sbox_pow, p - 1) = 1` there is a unique `k < sbox_pow` with
/// `k * (p - 1) + 1` divisible by `sbox_pow`, and the inverse exponent is
/// the exact quotient `(k * (p - 1) + 1) / sbox_pow`.
#[expect(clippy::single_call_fn, reason = "constant layout math")]
fn inverse_exponent(sbox_pow: u64) -> [u64; 4] {
    let p_minus_one = (-Fp::ONE).to_repr();

    // (p - 1) mod sbox_pow, folding bytes most-significant first.
    let residue = p_minus_one.iter().rev().fold(0u64, |acc, &byte| {
        ((acc << 8u32) | u64::from(byte))
            .checked_rem(sbox_pow)
            .expect("sbox_pow is nonzero")
    });

    let wraps = (1..sbox_pow)
        .find(|candidate| {
            candidate
                .checked_mul(residue)
                .and_then(|product| product.checked_add(1))
                .and_then(|sum| sum.checked_rem(sbox_pow))
                == Some(0)
        })
        .expect("gcd(sbox_pow, p - 1) must be 1");

    // numerator = wraps * (p - 1) + 1, little-endian with one overflow byte.
    let mut numerator = [0u8; 33];
    let mut carry = 1u64;
    for (out, &byte) in numerator.iter_mut().zip(p_minus_one.iter()) {
        let total = wraps
            .checked_mul(u64::from(byte))
            .and_then(|product| product.checked_add(carry))
            .expect("byte product fits u64");
        *out = u8::try_from(total & 0xff).expect("masked to a byte");
        carry = total >> 8u32;
    }
    numerator[32] = u8::try_from(carry).expect("carry of a small multiplier fits a byte");

    // Exact long division by sbox_pow, most-significant byte first.
    let mut quotient = [0u8; 33];
    let mut remainder = 0u64;
    for (out, &byte) in quotient.iter_mut().rev().zip(numerator.iter().rev()) {
        let current = (remainder << 8u32) | u64::from(byte);
        *out = u8::try_from(current.checked_div(sbox_pow).expect("sbox_pow is nonzero"))
            .expect("per-byte quotient fits a byte");
        remainder = current.checked_rem(sbox_pow).expect("sbox_pow is nonzero");
    }
    assert_eq!(remainder, 0, "k must make the numerator divisible");
    assert_eq!(quotient[32], 0, "inverse exponent must fit 256 bits");

    let mut limbs = [0u64; 4];
    for (limb, chunk) in limbs.iter_mut().zip(quotient[..32].chunks(8)) {
        let mut bytes = [0u8; 8];
        bytes.copy_from_slice(chunk);
        *limb = u64::from_le_bytes(bytes);
    }
    limbs
}
