//! Secret newtypes and in-place zeroization helpers for material whose
//! underlying types do not implement [`zeroize::Zeroize`].
//!
//! Each `Secret*` newtype owns the zeroize-on-drop behaviour for exactly one
//! concrete field/point type, so secret types elsewhere can wrap one and
//! `#[derive(Zeroize, ZeroizeOnDrop)]` instead of hand-writing the impls.
//! The free `wipe_*` helpers perform the volatile byte-wipe and are reused for
//! transient reddsa values that are not stored behind a `Secret*` newtype.

// TODO: this is kind of a mess. there are still lots of transient copies
// generated by computing operations on as_ref outputs. a real solution would
// require zeroize support in upstream pasta_curves.

#![allow(unsafe_code, clippy::inline_always, reason = "zeroization helpers")]
#![allow(dead_code, reason = "todo")]

use core::{mem::size_of, ptr, slice};

use derive_more::{Add, AddAssign, AsRef, Debug, Eq as TotalEq, From, Neg, PartialEq};
use pasta_curves::{EpAffine, Fp, Fq};
use zeroize::{Zeroize, ZeroizeOnDrop};

use crate::reddsa;

/// A secret Pallas base field element (`Fp`) that zeroizes itself on drop.
#[derive(Add, AddAssign, AsRef, Clone, Debug, From, Neg, PartialEq, TotalEq)]
pub(crate) struct SecretFp(#[debug(skip)] Fp);

impl Zeroize for SecretFp {
    fn zeroize(&mut self) {
        wipe_fp(&mut self.0);
    }
}

impl Drop for SecretFp {
    fn drop(&mut self) {
        self.zeroize();
    }
}

impl ZeroizeOnDrop for SecretFp {}

/// A secret Pallas scalar field element (`Fq`) that zeroizes itself on drop.
#[derive(Add, AddAssign, AsRef, Clone, Debug, From, Neg, PartialEq, TotalEq)]
pub(crate) struct SecretFq(#[debug(skip)] Fq);

impl Zeroize for SecretFq {
    fn zeroize(&mut self) {
        wipe_fq(&mut self.0);
    }
}

impl Drop for SecretFq {
    fn drop(&mut self) {
        self.zeroize();
    }
}

impl ZeroizeOnDrop for SecretFq {}

/// A secret Pallas point (`EpAffine`) that zeroizes itself on drop.
#[derive(AsRef, Clone, Debug, From, Neg, PartialEq, TotalEq)]
pub(crate) struct SecretEpAffine(#[debug(skip)] EpAffine);

impl Zeroize for SecretEpAffine {
    fn zeroize(&mut self) {
        wipe_ep_affine(&mut self.0);
    }
}

impl Drop for SecretEpAffine {
    fn drop(&mut self) {
        self.zeroize();
    }
}

impl ZeroizeOnDrop for SecretEpAffine {}

/// Volatile-wipe a Pallas scalar (`Fq`) in place.
#[inline(always)]
pub(crate) fn wipe_fq(value: &mut Fq) {
    // Safety: pasta_curves::Fq is a plain field element with no heap
    // allocations, internal pointers, or Drop implementation.
    unsafe {
        let bytes: *mut u8 = ptr::from_mut(value).cast();
        slice::from_raw_parts_mut(bytes, size_of::<Fq>()).zeroize();
    }
}

/// Volatile-wipe a Pallas base field element (`Fp`) in place.
#[inline(always)]
pub(crate) fn wipe_fp(value: &mut Fp) {
    // Safety: pasta_curves::Fp is a plain field element with no heap
    // allocations, internal pointers, or Drop implementation.
    unsafe {
        let bytes: *mut u8 = ptr::from_mut(value).cast();
        slice::from_raw_parts_mut(bytes, size_of::<Fp>()).zeroize();
    }
}

/// Volatile-wipe a Pallas point (`EpAffine`) in place.
#[inline(always)]
pub(crate) fn wipe_ep_affine(value: &mut EpAffine) {
    // Safety: pasta_curves::EpAffine is a plain curve point with no heap
    // allocations, internal pointers, or Drop implementation.
    unsafe {
        let bytes: *mut u8 = ptr::from_mut(value).cast();
        slice::from_raw_parts_mut(bytes, size_of::<EpAffine>()).zeroize();
    }
}

/// Volatile-wipe a reddsa verification key in place.
#[inline(always)]
pub(crate) fn wipe_reddsa_vk<T: reddsa::SigType>(value: &mut reddsa::VerificationKey<T>) {
    // Safety: reddsa::VerificationKey is a plain data struct (curve point),
    // with no heap allocations, internal pointers, or Drop implementation.
    unsafe {
        let bytes: *mut u8 = ptr::from_mut(value).cast();
        slice::from_raw_parts_mut(bytes, size_of::<reddsa::VerificationKey<T>>()).zeroize();
    }
}

/// Volatile-wipe a reddsa signing key in place.
#[inline(always)]
pub(crate) fn wipe_reddsa_sk<T: reddsa::SigType>(value: &mut reddsa::SigningKey<T>) {
    // Safety: reddsa::SigningKey is a plain data struct (curve point),
    // with no heap allocations, internal pointers, or Drop implementation.
    unsafe {
        let bytes: *mut u8 = ptr::from_mut(value).cast();
        slice::from_raw_parts_mut(bytes, size_of::<reddsa::SigningKey<T>>()).zeroize();
    }
}
