//! Generic committed-polynomial relations for step witnesses.

extern crate alloc;

use ff::{Field as _, PrimeField as _};
use pasta_curves::Fp;
use ragu::{Commitment, Domain, Polynomial};

const POLY_LEN_MAX: usize = 8192;

/// A primitive `ORDER`-th root of unity in `Fp`, generating the order-`ORDER`
/// evaluation-domain subgroup. `ORDER` is the domain size, not its log: a power
/// of two no larger than `2^Fp::S` (both checked at compile time).
pub(crate) fn subgroup_generator<const ORDER: usize>() -> Fp {
    const {
        assert!(
            ORDER.is_power_of_two(),
            "subgroup order must be a power of two"
        );
        assert!(
            ORDER.ilog2() <= Fp::S,
            "subgroup order exceeds the field's two-adicity"
        );
    }

    Domain::new(ORDER.ilog2()).omega()
}

/// Evaluate at `position` the unique polynomial of degree below `ORDER` that
/// takes `values[i]` at node `i` and is zero at every other `ORDER`-th root of
/// unity.
///
/// The nodes start at `node_start` and step by a primitive `VALUES`-th root
/// (computed internally), the spacing that lands them on the `ORDER`-th roots.
/// A *full* set (`VALUES = ORDER`, `node_start = 1`) covers every root; a
/// *sparse* set covers a sub-coset and is zero elsewhere. `vanishing` is the
/// `position^ORDER - 1` factor of the closed form, taken as an argument so a
/// caller that already holds it (the relation's domain divisor) does not
/// recompute it; callers must pass exactly `position^ORDER - 1`. Closed-form
/// subgroup-Lagrange interpolation, one inversion per node, with `n` = `ORDER`,
/// point `x` = `position`, nodes `a_i`, and values `v_i`:
///
/// $$
///     \sum_i v_i \, \frac{a_i}{x - a_i} \cdot \frac{x^{\,n} - 1}{n}.
/// $$
fn subgroup_interpolate<const ORDER: usize, const VALUES: usize>(
    values: &[Fp; VALUES],
    node_start: Fp,
    position: Fp,
    vanishing: Fp,
) -> Fp {
    const {
        assert!(ORDER != 0, "subgroup order must be nonzero");
    }

    #[expect(clippy::as_conversions, reason = "safe conversion")]
    let prefactor = vanishing
        * Fp::from(ORDER as u64)
            .invert()
            .expect("subgroup order must be nonzero");

    let node_step = subgroup_generator::<VALUES>();
    let mut accumulator = Fp::ZERO;
    let mut node = node_start;
    for &value in values {
        let denominator = (position - node)
            .invert()
            .expect("position should not coincide with a node");

        accumulator += value * node * denominator;
        node *= node_step;
    }
    accumulator * prefactor
}

/// Evaluate `position^ORDER - 1`, whose roots are exactly the `ORDER`-th roots
/// of unity: zero on that subgroup, nonzero elsewhere.
#[expect(clippy::as_conversions, reason = "safe conversion")]
fn zeroizer<const ORDER: usize>(position: Fp) -> Fp {
    position.pow_vartime([ORDER as u64]) - Fp::ONE
}

/// Prove that the committed `matrix` advances along each row by a fixed power
/// map. Read its domain evaluations row-major as rows of `COLUMNS` cells, over
/// the order-`POLY_LEN_MAX` domain generated by `g`, so the cell after the one
/// at `z` sits at $gz$. Each cell is the previous one plus its `offsets` term,
/// raised to the power `exponent`; the row's final cell is exempt, since its
/// successor starts a fresh row. As an identity at the Fiat-Shamir point `z`
/// (with `|D|` = `POLY_LEN_MAX`, `M` = `matrix`, `e` = `exponent`, mask $m$
/// vanishing on the final column, and offset $o$ interpolating `offsets`):
///
/// $$
///     m(z) \bigl( M(gz) - (M(z) + o(z))^{\,e} \bigr) = Q(z) \, (z^{|D|} - 1).
/// $$
///
/// The mask and offset are public closed forms in `z`. The quotient `Q` is
/// carried as `SPLITS` capacity-wide splits, about as many as the masked map's
/// degree $\approx e \, |D|$ requires. The relation derives `z` from `matrix`
/// and the splits, opens `matrix` at `z` and $gz$, recombines `Q(z)`, and
/// checks the identity.
///
/// # Caller obligations (soundness)
///
/// - **Binding.** `matrix` and every split must be commitment-bound to a
///   statement-fixed value (public input, prior-step output, or
///   transcript-absorbed commitment, not a fresh witness); all feed `z`.
/// - **Public structure.** `offsets` and `exponent` are not absorbed into `z`;
///   they must be statement-fixed, never witness-chosen after `z`.
pub(crate) fn enforce_row_recurrence<const COLUMNS: usize, const SPLITS: usize>(
    ctx: &mut ragu::StepCtx<'_>,
    matrix: &Polynomial,
    quotient: &[Polynomial; SPLITS],
    offsets: &[Fp; COLUMNS],
    exponent: u64,
) -> ragu::Result<()> {
    let matrix_commit = matrix.commit();
    let quotient_commits: [Commitment; SPLITS] = quotient.each_ref().map(Polynomial::commit);

    let z =
        ctx.derive_challenge(&[[matrix_commit].as_slice(), quotient_commits.as_slice()].concat())?;
    let vanishing = zeroizer::<POLY_LEN_MAX>(z);

    let matrix_at_z = matrix.eval(z);
    ctx.enforce_poly_query(matrix_commit, z, matrix_at_z)?;

    let quotient_at_z = {
        let stride = vanishing + Fp::ONE;
        let mut quotient_at_z = Fp::ZERO;
        let mut shift = Fp::ONE;
        for qt_p in quotient {
            let eval = qt_p.eval(z);
            ctx.enforce_poly_query(qt_p.commit(), z, eval)?;
            quotient_at_z += shift * eval;
            shift *= stride;
        }
        quotient_at_z
    };

    let znext = subgroup_generator::<POLY_LEN_MAX>() * z;
    let matrix_at_znext = matrix.eval(znext);
    ctx.enforce_poly_query(matrix_commit, znext, matrix_at_znext)?;

    #[expect(
        clippy::integer_division,
        clippy::integer_division_remainder_used,
        clippy::as_conversions,
        reason = "constant math"
    )]
    let period_position = z.pow_vartime([(POLY_LEN_MAX / COLUMNS) as u64]);

    // Mask end-of-row discontinuity at `g_sub^{COLUMNS-1} = g_sub^{-1}`
    let mask = period_position
        - subgroup_generator::<COLUMNS>()
            .invert()
            .expect("a root of unity is nonzero");

    // The offset interpolation's `position^COLUMNS - 1` factor is
    // `period_position^COLUMNS = z^|D|`, so its vanishing is the shared one.
    let offset =
        subgroup_interpolate::<COLUMNS, COLUMNS>(offsets, Fp::ONE, period_position, vanishing);

    let residual = matrix_at_znext - (matrix_at_z + offset).pow_vartime([exponent]);

    if mask * residual != quotient_at_z * vanishing {
        return Err(ragu::Error("row recurrence identity fails at challenge"));
    }
    Ok(())
}

/// Pin the *first column* of the committed `matrix` to prescribed values. Read
/// its domain evaluations as a matrix; the first column is the `ROWS`-th roots
/// of unity (one cell per row), pinned to `base + values[row]`. As an identity
/// at the Fiat-Shamir point `z` (with `|D|` = `POLY_LEN_MAX`, `R` = `ROWS`,
/// `M` = `matrix`, `b` = `base`, selector $s$, and interpolant $v$ of
/// `values`):
///
/// $$
///     s(z) \bigl( M(z) - b - v(z) \bigr) = Q(z) \, (z^{|D|} - 1).
/// $$
///
/// The constraint binds only the first column, so it does not fit the bare
/// $Q \cdot Z_D$ form: the selector $s(z) = (z^{|D|} - 1) / (z^{R} - 1)$
/// carries the $z^{|D|} - 1$ factor the check re-introduces, leaving the column
/// vanisher $z^{R} - 1$ as the effective divisor. The `quotient` has degree
/// below `POLY_LEN_MAX`, so it is one committed polynomial; the relation
/// derives `z` from `matrix` and `quotient`, opens both at `z`, and checks the
/// identity.
///
/// Callers needing a non-affine boundary (such as pinning each cell to an S-box
/// of its row input) precompute the per-row target into `values`; the relation
/// pins the column to whatever interpolant `values` describes.
///
/// # Caller obligations (soundness)
///
/// - **Binding.** `matrix` and `quotient` must be commitment-bound to a
///   statement-fixed value (not a fresh or merely-threaded witness); both feed
///   `z`.
/// - **Public structure.** `base` and `values` are not absorbed into `z`; fix
///   them to statement-fixed values, never witness-chosen after `z`.
pub(crate) fn enforce_first_column_values<const ROWS: usize>(
    ctx: &mut ragu::StepCtx<'_>,
    matrix: &Polynomial,
    quotient: &Polynomial,
    base: Fp,
    values: &[Fp; ROWS],
) -> ragu::Result<()> {
    let matrix_commit = matrix.commit();
    let quotient_commit = quotient.commit();

    let z = ctx.derive_challenge(&[matrix_commit, quotient_commit])?;

    let matrix_at_z = matrix.eval(z);
    ctx.enforce_poly_query(matrix_commit, z, matrix_at_z)?;
    let quotient_at_z = quotient.eval(z);
    ctx.enforce_poly_query(quotient_commit, z, quotient_at_z)?;

    let domain_vanishing = zeroizer::<POLY_LEN_MAX>(z);
    let rows_vanishing = zeroizer::<ROWS>(z);

    let values_at_z = subgroup_interpolate::<ROWS, ROWS>(values, Fp::ONE, z, rows_vanishing);

    let complement = domain_vanishing
        * rows_vanishing
            .invert()
            .expect("random challenge should not be a first-column root of unity");

    if complement * (matrix_at_z - base - values_at_z) != quotient_at_z * domain_vanishing {
        return Err(ragu::Error(
            "first column values identity fails at challenge",
        ));
    }
    Ok(())
}

/// Reduce the *final column* of the committed `matrix` to a per-row weighted
/// sum carried by the committed `reduction`. Read its domain evaluations
/// row-major as `POLY_LEN_MAX / ROWS` columns of `ROWS` cells, so the final
/// column is index `POLY_LEN_MAX / ROWS - 1`. As an identity at the Fiat-Shamir
/// point `z` (with `|D|` = `POLY_LEN_MAX`, `M` = `matrix`, `S` = `reduction`,
/// and weight `w` nonzero only on the final column):
///
/// $$
///     M(z) \, w(z) - S(z) = Q(z) \, (z^{|D|} - 1).
/// $$
///
/// This pins `reduction` to $M \cdot w$ reduced modulo the domain, so the two
/// agree on it and the constant-term lemma collapses the weighted column sum to
/// $|D| \cdot S(0)$, recovered from one opening of `reduction` at 0. The weight
/// interpolates `weights[row]` over the final column's coset, zero elsewhere.
/// The `quotient` has degree below `POLY_LEN_MAX`, so it is one committed
/// polynomial; the relation derives `z` from `matrix`, `reduction`, and
/// `quotient`, opens them at `z`, and checks the identity.
///
/// # Caller obligations (soundness)
///
/// - **Binding.** `matrix`, `reduction`, and `quotient` must be
///   commitment-bound to a statement-fixed value (not a fresh or
///   merely-threaded witness); all feed `z`.
/// - **Public structure.** `weights` (powers of a reduction parameter bound to
///   the commitments) are not absorbed into `z`; fix them before `z`.
/// - **Fresh opening.** A caller building `reduction`/`weights` from a
///   parameter must not reuse it as the opening position; `z` is derived after
///   `reduction` is absorbed, so it cannot be that parameter.
pub(crate) fn enforce_final_column_reduction<const ROWS: usize>(
    ctx: &mut ragu::StepCtx<'_>,
    matrix: &Polynomial,
    quotient: &Polynomial,
    reduction: &Polynomial,
    weights: &[Fp; ROWS],
) -> ragu::Result<()> {
    #[expect(clippy::integer_division_remainder_used, reason = "constant math")]
    const {
        assert!(
            POLY_LEN_MAX % ROWS == 0,
            "POLY_LEN_MAX must be evenly divisible by ROWS"
        );
    }

    let matrix_commit = matrix.commit();
    let reduction_commit = reduction.commit();
    let quotient_commit = quotient.commit();

    let z = ctx.derive_challenge(&[matrix_commit, reduction_commit, quotient_commit])?;
    let vanishing = zeroizer::<POLY_LEN_MAX>(z);

    let matrix_at_z = matrix.eval(z);
    ctx.enforce_poly_query(matrix_commit, z, matrix_at_z)?;
    let reduction_at_z = reduction.eval(z);
    ctx.enforce_poly_query(reduction_commit, z, reduction_at_z)?;
    let quotient_at_z = quotient.eval(z);
    ctx.enforce_poly_query(quotient_commit, z, quotient_at_z)?;

    // The weights are sparse: `ROWS` nonzero values on the final column's coset
    // of the order-`POLY_LEN_MAX` domain, zero elsewhere, so the interpolation
    // order is the whole domain.
    #[expect(
        clippy::integer_division,
        clippy::integer_division_remainder_used,
        clippy::as_conversions,
        reason = "constant math"
    )]
    let weight_node_start =
        subgroup_generator::<POLY_LEN_MAX>().pow_vartime([((POLY_LEN_MAX / ROWS) - 1) as u64]);
    let weight_at_z =
        subgroup_interpolate::<POLY_LEN_MAX, ROWS>(weights, weight_node_start, z, vanishing);

    if matrix_at_z * weight_at_z - reduction_at_z != quotient_at_z * vanishing {
        return Err(ragu::Error(
            "final column reduction identity fails at challenge",
        ));
    }
    Ok(())
}

#[cfg(test)]
#[expect(clippy::as_conversions, reason = "test code")]
mod tests {

    extern crate alloc;

    use alloc::vec::Vec;
    use core::iter::repeat_with;

    use ff::Field as _;
    use rand::{SeedableRng as _, rngs::StdRng};

    use super::*;

    /// Constant-term lemma: over the domain `D`, any polynomial `g` of degree
    /// below `|D|` has power sums that vanish except at exponent zero, so
    ///
    /// $$ \sum_{x \in D} g(x) = |D| \cdot g(0). $$
    ///
    /// The converter leans on it to collapse a domain sum to a single opening
    /// of `g` at zero. Checked on a 16-element domain.
    #[test]
    fn constant_term_lemma_on_a_small_domain() {
        const ORDER: usize = 16;
        let rng = &mut StdRng::seed_from_u64(0);

        let coeffs: Vec<Fp> = repeat_with(|| Fp::random(&mut *rng)).take(ORDER).collect();
        let poly = Polynomial::from_coeffs(&coeffs);

        let sum = {
            let root = subgroup_generator::<ORDER>();
            let mut sum = Fp::ZERO;
            let mut pos = Fp::ONE;
            for _ in 0..ORDER {
                sum += poly.eval(pos);
                pos *= root;
            }
            sum
        };

        {
            assert_eq!(
                sum,
                Fp::from(ORDER as u64) * poly.coefficients()[0],
                "sum over D of g must collapse to |D| * g(0)"
            );
        }
    }

    /// `subgroup_interpolate` (full set) reconstructs a polynomial from its
    /// values on the `ORDER`-th roots of unity: sampling a `deg < ORDER`
    /// polynomial on the roots and interpolating returns it at any off-node
    /// position. Checked against direct evaluation, an independent reference.
    #[test]
    fn subgroup_interpolate_reconstructs_a_full_value_set() {
        const ORDER: usize = 4;
        let rng = &mut StdRng::seed_from_u64(0);

        let coeffs: Vec<Fp> = repeat_with(|| Fp::random(&mut *rng)).take(ORDER).collect();
        let poly = Polynomial::from_coeffs(&coeffs);

        // Sample `poly` on the roots of unity.
        let values = {
            let mut values = [Fp::ZERO; ORDER];
            let root = subgroup_generator::<ORDER>();
            let mut node = Fp::ONE;
            for value in &mut values {
                *value = poly.eval(node);
                node *= root;
            }
            values
        };

        // Interpolating the samples reproduces `poly` away from the nodes.
        let challenge = Fp::random(rng);
        assert_eq!(
            subgroup_interpolate::<ORDER, ORDER>(
                &values,
                Fp::ONE,
                challenge,
                zeroizer::<ORDER>(challenge)
            ),
            poly.eval(challenge),
            "full interpolation must reconstruct the sampled polynomial",
        );
    }

    /// The recombination arithmetic `recombine_quotient` relies on: adjacent
    /// splits at the `POLY_LEN_MAX` stride evaluate, via Horner in
    /// `z^POLY_LEN_MAX`, to the unsplit polynomial's direct evaluation.
    #[test]
    fn quotient_splits_recombine_to_the_full_evaluation() {
        let rng = &mut StdRng::seed_from_u64(0);
        // Three capacities long, split adjacently.
        let full: Vec<Fp> = repeat_with(|| Fp::random(&mut *rng))
            .take(3 * POLY_LEN_MAX)
            .collect();
        let z = Fp::random(rng);

        let stride = z.pow_vartime([POLY_LEN_MAX as u64]);
        let mut combined = Fp::ZERO;
        let mut shift = Fp::ONE;
        for chunk in full.chunks(POLY_LEN_MAX) {
            combined += shift * Polynomial::from_coeffs(chunk).eval(z);
            shift *= stride;
        }

        let direct = full
            .iter()
            .rev()
            .fold(Fp::ZERO, |acc, &coeff| acc * z + coeff);
        assert_eq!(
            combined, direct,
            "adjacent splits must recombine to the full evaluation"
        );
    }
}
